export const reviews = [
	{
		id: 1,
		header: "A real sense of community nurtured",
		desc: "Really appreciate the help and support from the staff during these tough times. Shout out to Katie for her exceptional service!",
		author: "Olga",
		company: "Weave Studios - Kai Tak",
		star: 5,
		image: "/src/assets/oceanview.png",
	},
	{
		id: 2,
		header: "Perfect getaway experience",
		desc: "The booking process was seamless, and the hotel exceeded our expectations. The room was spacious, clean, and had a stunning view!",
		author: "James",
		company: "Sunset Resort - Bali",
		star: 4,
		image: "/src/assets/nightview.png",
	},
	{
		id: 3,
		header: "Amazing customer service",
		desc: "The staff went above and beyond to make our stay comfortable. Special thanks to Maria for arranging our tours and transfers.",
		author: "Sophia",
		company: "Ocean Breeze Hotel - Santorini",
		star: 5,
		image: "/src/assets/snowview.png",
	},
	{
		id: 4,
		header: "Luxurious and relaxing",
		desc: "The spa and pool facilities were top-notch. We felt pampered throughout our stay. Highly recommend this place!",
		author: "Michael",
		company: "Royal Palm Retreat - Maldives",
		star: 4,
		image: "/src/assets/oceanview.png",
	},
	{
		id: 5,
		header: "Great for family vacations",
		desc: "The kids loved the activities, and we enjoyed the peaceful environment. The food was delicious, and the staff was very friendly.",
		author: "Linda",
		company: "Happy Trails Resort - Phuket",
		star: 4,
		image: "/src/assets/snowview.png",
	},
	{
		id: 6,
		header: "Unforgettable honeymoon",
		desc: "Everything was perfect, from the romantic dinner setup to the private beach access. Thank you for making our honeymoon so special!",
		author: "Daniel",
		company: "Paradise Cove - Bora Bora",
		star: 5,
		image: "/src/assets/nightview.png",
	},
];
