export const listings = [
    {
        ratings: 4.5,
        remark: "Very Good",
        reviews: 54,
        cost: 244,
        amenities: 12,
        img: "/src/assets/cvk.png",
        address: "Gümüssuyu Mahallesi, Mete Cd. No:34, 34437 Beyoglu/İstanbul",
    },
    {
        ratings: 4.2,
        remark: "Very Good",
        reviews: 34,
        cost: 144,
        amenities: 12,
        img: "/src/assets/eresin.png",
        address: "Kucukayasofya Mahallesi, Mustafapasa Sokak No: 25, 34122",
    },
    {
        ratings: 5,
        remark: "Excellent",
        reviews: 128,
        cost: 420,
        amenities: 18,
        img: "/src/assets/carlton.png",
        address: "Al Sofouh Road, Dubai Marina",
    },
    {
        ratings: 4.3,
        remark: "Wonderful",
        reviews: 92,
        cost: 380,
        amenities: 15,
        img: "/src/assets/taj.png",
        address: "Pichola, Udaipur, Rajasthan 313001",
    },
];
